config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   root 'home#index'
   resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
# t.string   "title"
# t.decimal  "price",       precision: 16, scale: 2
# t.text     "description"
# t.string   "address"
# t.string   "postal_code"

	validates :title, presence: true
	validates :price, presence: true
	validates :address, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@items = Item.order('created_at DESC')
	end
	
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def new
		@item = Item.new
	end

	def create
		@item = Item.new(item_params)
		if @item.save
			#to do redirect to items index
			redirect_to root_path
		else
			render 'new'
		end
	end

	private

		def item_params
			params.require(:item).permit(:title, :price, :description, :address, :postal_code)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/home/index.html.erb
<div class="row">
	<% @items.each do |item| %>
		<div class="col-xs-6 col-md-3">
			<div class="panel panel-default">
			  <div class="panel-body">
			  	<!-- to-do need to to enable images-->
			    <img src="https://img1.etsystatic.com/068/2/6200203/il_570xN.785566047_psed.jpg" alt="product" class="item-image">
			  </div>
			  <div class="panel-footer">
			  	<div>
		  			<span class="item-title"><%= item.title %></span>
			  		<span class="item-price">$<%= item.price %></span>
			  	</div>
	
			  </div>
			</div>	
		</div>
	<% end %>
</div>

app/views/items/new.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
  	<div class="panel panel-info">
  		<div class="panel-heading">
  			<h2>Sell an item</h2>
  		</div>
  		<div class="panel-body">
		    <%= form_for(@item) do |f| %>
		    	<div class="error-msg">
		    		<% if @item.errors.any? %>
							<ul class="fa-ul">
  							<% @item.errors.full_messages.each do |msg| %>
    							<li><i class="fa-li fa fa-exclamation-triangle"></i><%= msg %></li>
  							<% end %>
							</ul>
						<% end %>
		    	</div>
		      <div class="form-group">
			      <%= f.label :title %>
			      <%= f.text_field :title, class: 'form-control' %>      	
		      </div>

		      <div class="form-group">
			      <%= f.label :price %>
			      <%= f.number_field :price, :step => 0.01, class: 'form-control' %>      	
		      </div>

		      <div class="form-group">
			      <%= f.label :description %>
			      <%= f.text_area :description, class: 'form-control' %>   
		      </div>

		      <div class="form-group">
			      <%= f.label :address %>
			      <%= f.text_field :address, class: 'form-control' %>      	
		      </div>

		      <div class="form-group">
			      <%= f.label :postal_code %>
			      <%= f.text_field :postal_code, class: 'form-control' %>      	
		      </div>
		      <%= f.submit "Post item", class: "btn btn-primary" %>
		    <% end %>
  		</div>
  	</div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Kijinstgram', root_path, class: 'navbar-brand' %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
  	    	
        <% if user_signed_in? %>
          <li><%= link_to "Sell an item", new_item_path, class: "navlink" %></li> 
          <li><%= link_to " #{current_user.email}" , edit_user_registration_path, class: "navlink" %></li>
          <li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kijinstagram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	 


<%= render "layouts/navbar" %>

<div class="container">
	<% if notice %><div class="alert alert-info"><%= notice %></div><% end %>
	<% if alert %><div class="alert alert-warning"><%= alert %></div><% end %>
	<%= yield %>
</div>


</body>
</html>